variable "env" {}
variable "cidr" {}
variable public_subnet {}
variable web_subnet {}
variable app_subnet {}
variable db_subnet {}
variable "availability_zones" {}
variable "default_vpc_id" {}
variable "default_vpc_rt" {}
variable "default_vpc_cidr" {}