variable "vpc" {}
variable "env" {}
variable "cidr" {}
variable public_subnet {}
variable web_subnet {}
variable app_subnet {}
variable db_subnet {}
variable "availability_zone" {}
variable "gateway_id" {}
