name: Provision Infrastructure
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
#  QA:
#    needs: dev
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run a one-line script
#        run: echo Hello, world!
#  UAT:
#    needs: QA
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run a one-line script
#        run: echo Hello, world!
#
#  Prod:
#    needs: UAT
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run a one-line script
#        run: echo Hello, world!